apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
  labels:
    app: krateo.io
    component: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      component: argocd
  template:
    metadata:
      labels:
        component: argocd
    spec:
      containers:
        - name: argocd
          image: {{ .Values.registry.images.argocd }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          env:
            - name: 'LOG_LEVEL'
              value: {{ .Values.log.level }}
            - name: 'ENDPOINT_URI'
              value: {{ .Values.uris.endpoint }}
            - name: 'MONGODB_URI'
              valueFrom:
                secretKeyRef:
                  name: krateo-secret
                  key: MONGODB_URI
      imagePullSecrets:
        - name: registry-credentials
